refactor(about): changed table to flexbox
jorgecarmona/zeever pull request #8
Opened 2023-07-03 20:42 UTC by valentinacastillo11

Trabajamos en el refactor About.  Se hicieron cambios en las tablas de HTML y en el CSS, ajustandolos a Flexbox.
![image](https://github.com/jorgecarmona/zeever/assets/138168094/bfe5df1b-f221-4437-9881-cab90f5750da)

2023-07-04 01:38 UTC, SGutierrez17 reviewed
@valentinacastillo11 @napito27 Revise el codigo y no se observa bien en el navegador
verificar que todos los cambios esten subidos para obtener la respuesta correcta de la revisión

2023-07-04 20:34 UTC, paulagutierrez08 commented
Buena tarde, @valentinacastillo11 @napito27 

Se ha revisado inicialmente la vista previa de la página web y se evidencia que:

- En sections, la  información no se encuentra en los contenedores, las imágenes no están correctamente ubicadas
![image](https://github.com/jorgecarmona/zeever/assets/137831678/3d2f274b-55cb-4f38-aaa2-7d385aa93317)

-En Services, no tiene los 6 contenedores, falta ubicarlos de manera horizontal y ubicar correctamente las imágenes.
![image](https://github.com/jorgecarmona/zeever/assets/137831678/f26b9627-77b3-44b8-ad9c-1c7b804f613b)

-En About, las tres imágenes no se evidencian 
![image](https://github.com/jorgecarmona/zeever/assets/137831678/12a71e88-0476-4f41-bc04-fbd72b327875)

-Testimonials esta repetido dos veces 
![image](https://github.com/jorgecarmona/zeever/assets/137831678/115a2d9d-eb06-4812-ae73-7b8eb57879ed)

Por favor revisar el código nuevamente para realizar las respectivas correcciones.

2023-07-06 20:52 UTC, SGutierrez17 commented
@napito27 @valentinacastillo11 revisando la modificación hecha encuentro que hay un padding que modifica la margen y hace que no sea similar al archivo original.
![image](https://github.com/jorgecarmona/zeever/assets/136516495/143a1f95-c5cc-4c33-a3b9-0d32488e31f2)

2023-07-06 23:02 UTC, jorgecarmona commented on index.html
> +         <div class="about-section section">
change this to:
`<div class="about-section">`

2023-07-06 23:03 UTC, jorgecarmona requested changes
Left a comment

2023-07-06 23:12 UTC, jorgecarmona approved these changes
Looks good

2023-07-06 23:12 UTC, SGutierrez17 approved these changes
looks good

2023-07-06 23:13 UTC, merged